In [19]:
%load_ext autoreload
%autoreload 2

# Set working directory to parent directory
%cd ..
sky_slam_path = str(_dh[1]) # Store second entry in dir history so we always revert there (hacky!)
%cd $sky_slam_path

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
/Users/tomish/Projects
/Users/tomish/Projects/antworld


In [20]:
import os
import re
import numpy as np
import scipy as sp
import scipy.io as sio # To import Matlab stuff

In [21]:
world_folder = 'data/seville'
world_name = 'world5000_gray'
ml_file_name = os.path.join(world_folder, world_name + '.mat')
matlab_world  = sio.loadmat(ml_file_name)

Remove items from dictionary where key starts with double underscore 

In [22]:
data_matrices = dict((k, v) for k, v in matlab_world.items() if not re.search("__[A-Za-z0-9]*", k))

Save compressed numpy file

In [23]:
np_file_name = os.path.join(world_folder, world_name + '.npz')
np.savez_compressed(np_file_name, **data_matrices)

Test it works by loading again

In [24]:
data = np.load(np_file_name)
print data['X']
print data['Y']
print data['Z']
print data['colp'] # This isn't in all the ant worlds. Is colour information

[[ 7.99211326  8.08788674  7.84891257]
 [ 8.8244461   8.8555539   8.77173313]
 [ 8.60982153  8.51017847  8.39728369]
 ..., 
 [ 8.72741478  8.81258522  8.74761589]
 [ 0.09166514  0.16833486  0.28047766]
 [ 2.90354858  2.99645142  3.1518319 ]]
[[ 9.10438262  9.07561738  9.1377172 ]
 [ 7.12751922  7.03248078  7.14167196]
 [ 4.07577917  4.08422083  4.01881486]
 ..., 
 [ 7.21620113  7.16379887  7.23285756]
 [ 5.91789955  5.98210045  5.93105249]
 [ 6.74850042  6.71149958  6.79068952]]
[[ 0.          0.          0.05406266]
 [ 0.          0.          0.15061429]
 [ 0.          0.          0.14862644]
 ..., 
 [ 0.          0.          0.18883355]
 [ 0.          0.          0.35842479]
 [ 0.          0.          0.0688574 ]]
[[ 0.33816725  0.33816725  0.33816725]
 [ 0.34506611  0.34506611  0.34506611]
 [ 0.36240004  0.36240004  0.36240004]
 ..., 
 [ 0.49155629  0.49155629  0.49155629]
 [ 0.57588239  0.57588239  0.57588239]
 [ 0.49515778  0.49515778  0.49515778]]
